# Generated by Django 4.2.5 on 2025-02-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='Customer',
        ),
    ]
